app:
  name: "task-processor"
  version: "1.0.0"
  env: "development"

http:
  port: "8080"
  read_timeout: "5s"
  write_timeout: "10s"
  idle_timeout: "60s"

log:
  level: "debug"

postgres:
  url: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"
  migrationsDir: "./migrations"
  max_pool_size: 50
  min_pool_size: 10
  max_conn_lifetime: "1h"
  max_conn_idle_time: "30m"  
  connect_timeout: "5s"

redis:
  address: "redis:6379"
  password: ""                    
  db: 0                           
  pool_size: 10                   
  dial_timeout: "5s"              
  read_timeout: "3s"             
  write_timeout: "3s"

worker_pool:
  max_workers: 10

rate_limit:
  rps:    100          
  burst:  150     
  period: "1s"

circuit_breaker:
  enabled: true
  max_requests: 3
  interval: 60s
  timeout: 30s
  consecutive_failures: 5

healthcheck:
  timeout: "3s"

shutdown:
  http_timeout: "5s"
  hard_period: "3s"
  readiness_drain: "5s"