services:
  task-processor:
    build: .
    container_name: task-processor
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./config-local.yaml:/app/config-local.yaml
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    container_name: task-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: task-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
